"""empty message

Revision ID: 793056287017
Revises: bea8a9545160
Create Date: 2023-11-25 08:31:19.356619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '793056287017'
down_revision = 'bea8a9545160'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
