"""empty message

Revision ID: 818e5a264273
Revises: d7867ef4dc05
Create Date: 2023-11-07 19:09:38.342042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '818e5a264273'
down_revision = 'd7867ef4dc05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('professor',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('idade', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('professor')
    # ### end Alembic commands ###
